minimumReleaseAge: 1440
shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  sharp: true
  '@swc/core': true
